#!/bin/sh
rew cask install notational-velocity
brew cask install evernote
brew cask install atext
brew cask install google-chrome
brew cask install sparrow
brew cask install audacity
brew cask install skype
brew cask install vlc
brew cask install handbrake
brew cask install plex-media-server
brew cask install spotify
brew cask install dropbox
brew cask install skitch
brew cask install crashplan
brew cask install the-unarchiver
brew cask install mindjet-mindmanager
brew cask install pycharm-edu
brew cask install github-desktop
brew cask install sopcast
brew cask install pgadmin3
brew cask install flickr-uploader
brew cask install google-photos-backup
brew cask install google-earth
brew cask install google-drive
brew cask install sequel-pro
brew cask install mysql-utilities
brew cask install mysql-workbench
brew cask install diskmaker-x
brew cask install onyx
brew cask install logitech-harmony
brew cask install mobile-mouse-server
brew cask install caffeine
brew cask install calibre
brew cask install slack
brew cask install kodi
brew cask install firefox
